import Head from "next/head"
import { Inter } from "next/font/google"
import styles from "@/styles/Home.module.css"
// import ManualHeader from "@/Components/ManualHeader"
import Header from "../components/Header"
import RaffleEntrance from "@/components/RaffleEntrance"

const inter = Inter({ subsets: ["latin"] })

export default function Home() {
    return (
        <>
            <Head>
                <title>Raffle</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            {/* <ManualHeader /> */}
            <RaffleEntrance />
        </>
    )
}
